# Generated by Django 6.1 on 2026-09-10 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_sitelogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Drinks, Electronics, Vehicles, Fashion.', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='Short line shown under the name, e.g. "Wholesale & retail, delivered nationwide".', max_length=150)),
                ('theme', models.CharField(choices=[('green', 'Green & gold (drinks, food, everyday goods)'), ('blue', 'Blue & cyan (electronics, tech, gadgets)'), ('crimson', 'Crimson & steel (vehicles, motorbikes, hardware)'), ('violet', 'Violet & rose (fashion, beauty, lifestyle)'), ('amber', 'Amber & bronze (general / anything else)')], default='green', max_length=10)),
                ('icon_kind', models.CharField(choices=[('bottle', 'Bottle'), ('glass', 'Glass'), ('can', 'Can'), ('truck', 'Delivery truck'), ('gift', 'Gift'), ('star', 'Star')], default='bottle', help_text='Placeholder icon used where a product in this department has no photo.', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Which department this category belongs to (Drinks, Electronics, etc).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='store.department'),
        ),
    ]
