# Generated by Django 6.1 on 2026-09-10 18:26

from django.db import migrations


def create_drinks_department(apps, schema_editor):
    Department = apps.get_model('store', 'Department')
    Category = apps.get_model('store', 'Category')

    drinks, _ = Department.objects.get_or_create(
        slug='drinks',
        defaults={
            'name': 'Drinks',
            'tagline': 'Sodas, juices, water & more, delivered cold.',
            'theme': 'green',
            'icon_kind': 'bottle',
            'sort_order': 0,
        },
    )
    Category.objects.filter(department__isnull=True).update(department=drinks)


def reverse(apps, schema_editor):
    pass  # nothing to undo — leaving categories linked is harmless


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_department_category_department'),
    ]

    operations = [
        migrations.RunPython(create_drinks_department, reverse),
    ]
