# Generated by Django 6.1.1 on 2026-09-13 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_backfill_drinks_department'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Platform-owned products are auto-approved. Vendor listings default to unapproved until admin reviews them — see the "Approve selected products" admin action.'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text="Leave blank for products the platform itself sells. Set this for a third-party seller's listing.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendor'),
        ),
    ]
