# Generated by Django 6.1.1 on 2026-09-19 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_is_approved_product_vendor'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Which top-level department this product belongs to. Auto-filled from the category if left blank.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.department'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['department', 'is_active', 'is_approved'], name='store_produ_departm_55e676_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active', 'is_approved'], name='store_produ_categor_a65d51_idx'),
        ),
    ]
