# Generated by Django 6.1.1 on 2026-09-19 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='unit_kind',
            field=models.CharField(choices=[('volume', 'Volume (ml / L)'), ('weight', 'Weight (g / kg)'), ('screen', 'Screen size (inches)'), ('none', 'No size variants')], default='none', help_text='Controls the "size" label shown on the product page and the unit used on variants. Drinks → volume, Electronics → screen, groceries → weight.', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('last_chance', 'Last chance'), ('unavailable', 'Temporarily unavailable'), ('discontinued', 'No longer available')], default='available', help_text='Controls the badge and whether "Add to cart" is enabled.', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional "was" price. Shows a discount badge when higher than price.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Main product photo. Additional gallery photos go in the "Images" section below.', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fallback price in KES. Prefer setting prices on variants below.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Fallback stock if no variants.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='volume_ml',
            field=models.PositiveIntegerField(blank=True, help_text='Legacy single-size field. Use variants for multi-size products.', null=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Short description of what the photo shows, for screen readers.', max_length=150)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. 0 = main photo.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='e.g. "Save 20% off TV Wall Mounts when you buy a TV"', max_length=200)),
                ('url', models.CharField(blank=True, help_text='Optional link. Leave blank for plain text.', max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='store.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_label', models.CharField(help_text='Shown on the size selector button, e.g. 32", 500ml, 1kg.', max_length=40)),
                ('size_value', models.DecimalField(blank=True, decimal_places=2, help_text='Optional numeric value for sorting/filtering, e.g. 500 for 500ml.', max_digits=8, null=True)),
                ('size_unit', models.CharField(blank=True, choices=[('', '— (no unit)'), ('in', 'Inches'), ('ml', 'Millilitres'), ('l', 'Litres'), ('g', 'Grams'), ('kg', 'Kilograms'), ('cm', 'Centimetres'), ('pack', 'Pack')], default='', help_text='Unit that size_value is expressed in.', max_length=10)),
                ('sku', models.CharField(blank=True, help_text='Optional stock-keeping unit for this exact size.', max_length=64)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in KES', max_digits=8)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Optional "was" price for this size.', max_digits=8, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True, help_text='Turn off to hide this size without deleting it.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
            ],
            options={
                'ordering': ['sort_order', 'price'],
                'unique_together': {('product', 'size_label')},
            },
        ),
    ]
