# Generated by Django 6.1.1 on 2026-09-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_department_unit_kind_product_availability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A label for you, e.g. "Main Shopify Store".', max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('shopify', 'Shopify')], default='shopify', max_length=20)),
                ('store_domain', models.CharField(help_text='e.g. your-store.myshopify.com (no https://, no trailing slash).', max_length=200)),
                ('client_id', models.CharField(blank=True, help_text='Shopify app Client ID from the Dev Dashboard → App settings.', max_length=120)),
                ('client_secret', models.CharField(blank=True, help_text='Shopify app Client Secret. Treat like a password.', max_length=200)),
                ('api_version', models.CharField(default='2024-10', help_text='Shopify Admin API version, e.g. 2024-10.', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Disable to stop this source from being synced.')),
                ('auto_approve', models.BooleanField(default=True, help_text='If off, imported products land in "pending approval" and you review them in Products admin before they go live.')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('ok', 'OK'), ('error', 'Error'), ('never', 'Never synced')], default='never', max_length=10)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('default_department', models.ForeignKey(blank=True, help_text='Department to assign when the Shopify product has no match.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_sources', to='store.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
