# Generated by Django 6.1.1 on 2026-09-21 13:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0013_department_unit_kind_product_availability_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, help_text='Shown to users under the media, optional.')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='marketing/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='marketing/videos/')),
                ('caption_suggestion', models.TextField(blank=True, help_text='Suggested WhatsApp caption. Users can copy this with one tap.')),
                ('payout_per_view', models.DecimalField(decimal_places=2, default=50, help_text='KES paid to the sharer for each unique view of their link.', max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Turn off to stop new shares and stop counting views.')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Leave blank to keep it running until you turn it off.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, help_text='The product this campaign promotes. Shared links land here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_campaigns', to='store.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_view_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='marketing.marketingcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'campaign')},
            },
        ),
        migrations.CreateModel(
            name='MarketingPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.PositiveIntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('accruing', 'Accruing'), ('requested', 'Payout requested'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='accruing', max_length=10)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='marketing.marketingcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
                'unique_together': {('user', 'campaign')},
            },
        ),
        migrations.CreateModel(
            name='MarketingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('referer', models.CharField(blank=True, max_length=300)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_rows', to='marketing.marketingshare')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['share', 'fingerprint'], name='marketing_m_share_i_3ecead_idx')],
                'unique_together': {('share', 'fingerprint')},
            },
        ),
    ]
