# Generated by Django 6.1.1 on 2026-09-21 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingcampaign',
            name='caption_suggestion',
            field=models.TextField(blank=True, help_text='Suggested WhatsApp caption. Users can copy this with one tap. Use {{LINK}} as a placeholder for the share URL.'),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='payout_per_view',
            field=models.DecimalField(decimal_places=2, default=50, help_text='KES paid to the sharer for each view credited to their share.', max_digits=6),
        ),
        migrations.CreateModel(
            name='MarketingProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='marketing/proofs/%Y/%m/')),
                ('reported_views', models.PositiveIntegerField(help_text='Type the number you see in your screenshot.')),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending (24h hold)'), ('approved', 'Approved & credited'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('payout_due_at', models.DateTimeField(db_index=True, help_text='When the 24-hour hold expires and the payout can run.')),
                ('credited_at', models.DateTimeField(blank=True, null=True)),
                ('credited_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confirmation_sent_at', models.DateTimeField(blank=True, null=True)),
                ('congrats_sent_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='marketing.marketingshare')),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['status', 'payout_due_at'], name='marketing_m_status_7046e3_idx')],
            },
        ),
    ]
